stages:
  - deploy

deploy_main:
  stage: deploy
  tags:
    - video
  only:
    - main
  script:
    - cd /opt/videoconferencing
    - git fetch --all --prune
    - git reset --hard origin/main
    - source /opt/videoconferencing/venv/bin/activate
    - pip install -r requirements.txt
#    - python manage.py migrate
    - python manage.py collectstatic --noinput
    - sudo /usr/local/bin/restart_gunicorn.sh